name: Run Check My Code

on: [push , pull_request]

jobs:
    call-checkMycode:
      uses: athleticim/builder-helper/.github/workflows/checkmycode-helper.yml@main
      secrets:
        ORG_NPM_INSTALL : ${{secrets.ORG_NPM_INSTALL}} 